/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package crms.form;

/**
 *
 * @author u1ben
 */
public class MainForm extends javax.swing.JFrame {

    /**
     * Creates new form MainForm
     */
    public MainForm() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlRoot = new javax.swing.JPanel();
        pnlSide = new javax.swing.JPanel();
        space1 = new javax.swing.JPanel();
        title1 = new javax.swing.JLabel();
        title2 = new javax.swing.JLabel();
        space2 = new javax.swing.JPanel();
        jSeparator1 = new javax.swing.JSeparator();
        space3 = new javax.swing.JPanel();
        btnReg = new javax.swing.JButton();
        space4 = new javax.swing.JPanel();
        btnReg1 = new javax.swing.JButton();
        space5 = new javax.swing.JPanel();
        btnReg2 = new javax.swing.JButton();
        pnlCenter = new javax.swing.JPanel();
        tblCar = new javax.swing.JPanel();
        lblBrand = new javax.swing.JLabel();
        txtBrand = new javax.swing.JTextField();
        lblModel = new javax.swing.JLabel();
        txtModel = new javax.swing.JTextField();
        lblDesc = new javax.swing.JLabel();
        txtDesc = new javax.swing.JTextField();
        lblPrice = new javax.swing.JLabel();
        txtPrice = new javax.swing.JTextField();
        space6 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        pnlRoot.setPreferredSize(new java.awt.Dimension(777, 507));
        pnlRoot.setLayout(new java.awt.BorderLayout());

        pnlSide.setBackground(new java.awt.Color(21, 25, 28));
        pnlSide.setPreferredSize(new java.awt.Dimension(150, 0));
        pnlSide.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 6, 8));

        space1.setBackground(new java.awt.Color(21, 25, 28));
        space1.setPreferredSize(new java.awt.Dimension(170, 50));

        javax.swing.GroupLayout space1Layout = new javax.swing.GroupLayout(space1);
        space1.setLayout(space1Layout);
        space1Layout.setHorizontalGroup(
            space1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 170, Short.MAX_VALUE)
        );
        space1Layout.setVerticalGroup(
            space1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 50, Short.MAX_VALUE)
        );

        pnlSide.add(space1);

        title1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        title1.setForeground(new java.awt.Color(252, 252, 252));
        title1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        title1.setText("Car");
        title1.setPreferredSize(new java.awt.Dimension(150, 29));
        pnlSide.add(title1);

        title2.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        title2.setForeground(new java.awt.Color(252, 252, 252));
        title2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        title2.setText("Rental");
        title2.setPreferredSize(new java.awt.Dimension(150, 29));
        pnlSide.add(title2);

        space2.setBackground(new java.awt.Color(21, 25, 28));
        space2.setPreferredSize(new java.awt.Dimension(170, 10));

        javax.swing.GroupLayout space2Layout = new javax.swing.GroupLayout(space2);
        space2.setLayout(space2Layout);
        space2Layout.setHorizontalGroup(
            space2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 170, Short.MAX_VALUE)
        );
        space2Layout.setVerticalGroup(
            space2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 10, Short.MAX_VALUE)
        );

        pnlSide.add(space2);

        jSeparator1.setPreferredSize(new java.awt.Dimension(120, 10));
        pnlSide.add(jSeparator1);

        space3.setBackground(new java.awt.Color(21, 25, 28));
        space3.setPreferredSize(new java.awt.Dimension(170, 10));

        javax.swing.GroupLayout space3Layout = new javax.swing.GroupLayout(space3);
        space3.setLayout(space3Layout);
        space3Layout.setHorizontalGroup(
            space3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 170, Short.MAX_VALUE)
        );
        space3Layout.setVerticalGroup(
            space3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 10, Short.MAX_VALUE)
        );

        pnlSide.add(space3);

        btnReg.setBackground(new java.awt.Color(21, 25, 28));
        btnReg.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnReg.setForeground(new java.awt.Color(204, 204, 204));
        btnReg.setText("Registration");
        btnReg.setBorder(null);
        btnReg.setPreferredSize(new java.awt.Dimension(150, 22));
        btnReg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegActionPerformed(evt);
            }
        });
        pnlSide.add(btnReg);

        space4.setBackground(new java.awt.Color(21, 25, 28));
        space4.setPreferredSize(new java.awt.Dimension(170, 10));

        javax.swing.GroupLayout space4Layout = new javax.swing.GroupLayout(space4);
        space4.setLayout(space4Layout);
        space4Layout.setHorizontalGroup(
            space4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 170, Short.MAX_VALUE)
        );
        space4Layout.setVerticalGroup(
            space4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 10, Short.MAX_VALUE)
        );

        pnlSide.add(space4);

        btnReg1.setBackground(new java.awt.Color(21, 25, 28));
        btnReg1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnReg1.setForeground(new java.awt.Color(204, 204, 204));
        btnReg1.setText("Inventory");
        btnReg1.setBorder(null);
        btnReg1.setPreferredSize(new java.awt.Dimension(150, 22));
        btnReg1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReg1ActionPerformed(evt);
            }
        });
        pnlSide.add(btnReg1);

        space5.setBackground(new java.awt.Color(21, 25, 28));
        space5.setPreferredSize(new java.awt.Dimension(170, 10));

        javax.swing.GroupLayout space5Layout = new javax.swing.GroupLayout(space5);
        space5.setLayout(space5Layout);
        space5Layout.setHorizontalGroup(
            space5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 170, Short.MAX_VALUE)
        );
        space5Layout.setVerticalGroup(
            space5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 10, Short.MAX_VALUE)
        );

        pnlSide.add(space5);

        btnReg2.setBackground(new java.awt.Color(21, 25, 28));
        btnReg2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnReg2.setForeground(new java.awt.Color(204, 204, 204));
        btnReg2.setText("Rent");
        btnReg2.setBorder(null);
        btnReg2.setPreferredSize(new java.awt.Dimension(150, 22));
        btnReg2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReg2ActionPerformed(evt);
            }
        });
        pnlSide.add(btnReg2);

        pnlRoot.add(pnlSide, java.awt.BorderLayout.WEST);

        pnlCenter.setBackground(new java.awt.Color(34, 40, 44));
        pnlCenter.setPreferredSize(new java.awt.Dimension(777, 507));

        tblCar.setBackground(new java.awt.Color(34, 40, 44));

        lblBrand.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblBrand.setForeground(new java.awt.Color(204, 204, 204));
        lblBrand.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblBrand.setText("Brand");
        lblBrand.setPreferredSize(new java.awt.Dimension(200, 40));
        tblCar.add(lblBrand);

        txtBrand.setBackground(new java.awt.Color(44, 52, 58));
        txtBrand.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtBrand.setForeground(new java.awt.Color(255, 255, 255));
        txtBrand.setBorder(null);
        txtBrand.setCaretColor(new java.awt.Color(255, 255, 255));
        txtBrand.setPreferredSize(new java.awt.Dimension(200, 30));
        txtBrand.setSelectionColor(new java.awt.Color(204, 204, 204));
        tblCar.add(txtBrand);

        lblModel.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblModel.setForeground(new java.awt.Color(204, 204, 204));
        lblModel.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblModel.setText("Model");
        lblModel.setPreferredSize(new java.awt.Dimension(200, 40));
        tblCar.add(lblModel);

        txtModel.setBackground(new java.awt.Color(44, 52, 58));
        txtModel.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtModel.setForeground(new java.awt.Color(255, 255, 255));
        txtModel.setBorder(null);
        txtModel.setCaretColor(new java.awt.Color(255, 255, 255));
        txtModel.setPreferredSize(new java.awt.Dimension(200, 30));
        txtModel.setSelectionColor(new java.awt.Color(204, 204, 204));
        tblCar.add(txtModel);

        lblDesc.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblDesc.setForeground(new java.awt.Color(204, 204, 204));
        lblDesc.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblDesc.setText("Description");
        lblDesc.setPreferredSize(new java.awt.Dimension(200, 40));
        tblCar.add(lblDesc);

        txtDesc.setBackground(new java.awt.Color(44, 52, 58));
        txtDesc.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtDesc.setForeground(new java.awt.Color(255, 255, 255));
        txtDesc.setBorder(null);
        txtDesc.setCaretColor(new java.awt.Color(255, 255, 255));
        txtDesc.setPreferredSize(new java.awt.Dimension(200, 30));
        txtDesc.setSelectionColor(new java.awt.Color(204, 204, 204));
        tblCar.add(txtDesc);

        lblPrice.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblPrice.setForeground(new java.awt.Color(204, 204, 204));
        lblPrice.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblPrice.setText("Price");
        lblPrice.setPreferredSize(new java.awt.Dimension(200, 40));
        tblCar.add(lblPrice);

        txtPrice.setBackground(new java.awt.Color(44, 52, 58));
        txtPrice.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtPrice.setForeground(new java.awt.Color(255, 255, 255));
        txtPrice.setBorder(null);
        txtPrice.setCaretColor(new java.awt.Color(255, 255, 255));
        txtPrice.setPreferredSize(new java.awt.Dimension(200, 30));
        txtPrice.setSelectionColor(new java.awt.Color(204, 204, 204));
        tblCar.add(txtPrice);

        space6.setBackground(new java.awt.Color(34, 40, 44));
        space6.setPreferredSize(new java.awt.Dimension(224, 26));

        javax.swing.GroupLayout space6Layout = new javax.swing.GroupLayout(space6);
        space6.setLayout(space6Layout);
        space6Layout.setHorizontalGroup(
            space6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 224, Short.MAX_VALUE)
        );
        space6Layout.setVerticalGroup(
            space6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 26, Short.MAX_VALUE)
        );

        tblCar.add(space6);

        jButton1.setBackground(new java.awt.Color(44, 52, 58));
        jButton1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButton1.setForeground(new java.awt.Color(204, 204, 204));
        jButton1.setText("Register");
        jButton1.setPreferredSize(new java.awt.Dimension(100, 34));
        tblCar.add(jButton1);

        jTable1.setBackground(new java.awt.Color(44, 52, 58));
        jTable1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Brand", "Model", "Description", "Price"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Double.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jTable1.setPreferredSize(new java.awt.Dimension(250, 80));
        jScrollPane1.setViewportView(jTable1);

        javax.swing.GroupLayout pnlCenterLayout = new javax.swing.GroupLayout(pnlCenter);
        pnlCenter.setLayout(pnlCenterLayout);
        pnlCenterLayout.setHorizontalGroup(
            pnlCenterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlCenterLayout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addComponent(tblCar, javax.swing.GroupLayout.PREFERRED_SIZE, 229, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(49, 49, 49)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 636, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(245, Short.MAX_VALUE))
        );
        pnlCenterLayout.setVerticalGroup(
            pnlCenterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlCenterLayout.createSequentialGroup()
                .addContainerGap(94, Short.MAX_VALUE)
                .addGroup(pnlCenterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 513, Short.MAX_VALUE)
                    .addComponent(tblCar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(68, 68, 68))
        );

        pnlRoot.add(pnlCenter, java.awt.BorderLayout.CENTER);

        getContentPane().add(pnlRoot, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnRegActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnRegActionPerformed

    private void btnReg1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReg1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnReg1ActionPerformed

    private void btnReg2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReg2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnReg2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnReg;
    private javax.swing.JButton btnReg1;
    private javax.swing.JButton btnReg2;
    private javax.swing.JButton jButton1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTable jTable1;
    private javax.swing.JLabel lblBrand;
    private javax.swing.JLabel lblDesc;
    private javax.swing.JLabel lblModel;
    private javax.swing.JLabel lblPrice;
    private javax.swing.JPanel pnlCenter;
    private javax.swing.JPanel pnlRoot;
    private javax.swing.JPanel pnlSide;
    private javax.swing.JPanel space1;
    private javax.swing.JPanel space2;
    private javax.swing.JPanel space3;
    private javax.swing.JPanel space4;
    private javax.swing.JPanel space5;
    private javax.swing.JPanel space6;
    private javax.swing.JPanel tblCar;
    private javax.swing.JLabel title1;
    private javax.swing.JLabel title2;
    private javax.swing.JTextField txtBrand;
    private javax.swing.JTextField txtDesc;
    private javax.swing.JTextField txtModel;
    private javax.swing.JTextField txtPrice;
    // End of variables declaration//GEN-END:variables
}
